; help text for the build in functions
; get this into the lisp system by (load 'helptext.lsp)

; (obl 10) returns a list of Subr names
(defun help verb
  (cond
    ((null verb) (print "No argument, these are all Subrs:") (obl 10))
    ((member (eval (quote (car verb))) (obl 10)) (print "Helptext:")
						(get (car verb) 'helptext) )
    (t (print (car verb)) (print "is not valid Subr name. Also try (oblist) for lisp defined functions. These are the Subrs:") (obl 10))
  )
)


; help text stored as properties for each Subr

(put   'quote 'helptext "quotes s-exp.  Also ' and matched double quotes" )
(put   'true 'helptext "(true) returns true, the true value" )
(put   'eval 'helptext "starts evaluation of the s-exp" )
(put   'lambda 'helptext "Define function. See delete or defun to see example. NB defun fn (arg)... and defun fn arg... differ in eval/not eval arg.")
(put   'cdr 'helptext "(cdr 'a 'b 'c) is (b c)" )
(put   'car 'helptext "(car 'a 'b 'c) is a" )
(put   'cons 'helptext "(cons 'a 'b) is (a b)" )
(put   'and 'helptext "(and a b c) returns true if all of a, b, c are true. Will shortcut" )
(put   'or 'helptext "(or a b c) returns true if any of a, b, c are true. Will shortcut." )
(put   'cond 'helptext "The if function, chain of conditions" )
(put   'list 'helptext "Makes a list. (list 'a 'b 'c) is (a b c)" )
(put   'loop 'helptext "Starts loop, terminates on while or until" )
(put   'while 'helptext "(while a) will terminate enclosing loop when a false" )
(put   'until 'helptext "(until a) will terminate enclosing loop when a true" )
(put   'set 'helptext "(set a b) evaluates a, b then sets a to the b result" )
(put   'setq 'helptext "(setq a b)  evaluates b then sets a to the b result" )
(put   'eof 'helptext "(eof filehandle) returns true when file at end" )
(put   'ordinal 'helptext "(ordinal 'A) returns 65" )
(put   'minusp 'helptext "Returns true if the number is negative" )
(put   'system 'helptext "Spawns to shell with quoted string" )
(put   '+ 'helptext "(+ 3 2.5) returns 5.5" )
(put   '* 'helptext "(* 3 2.5) returns 7.5" )
(put   '- 'helptext "(- 4 2) returns 2" )
(put   '/ 'helptext "(/ 16 4) returns 4" )
(put   'sqrt 'helptext "(sqrt 4) returns 2" )
(put   'listp 'helptext "returns true if argument is a list" )
(put   'numberp 'helptext "returns true if the argument is a number" )
(put   'atom 'helptext "returns true if argument is an atom (including number)" )
(put   'null 'helptext "(null ()) returns true if arg is false" )
(put   'not 'helptext "(not) returns true if arg is false" )
(put   'length 'helptext "length of a top level list" )
(put   'obl 'helptext "various help functions, use (obl) or (obl n) 1 to 10" )
(put   'print 'helptext "prints the s-exp, space between atoms" )
(put   'prin 'helptext "prints the s-exp with no spaces between atoms" )
(put   'eq 'helptext "true if atoms or list the same. Type equal to see more general function." )
(put   'load 'helptext "loads a lisp file into memory. (load 'file)" )
(put   'readch 'helptext "(readch fh) reads character from open file" )
(put   'explode 'helptext "(explode (quote the)) is (t h e)" )
(put   'write 'helptext "(write fh s-exp) like print to an open file" )
(put   'read 'helptext "(read fh) reads an s-exp from file" )
(put   'open 'helptext "(open './file) returns fh if file readable, else null. Arg not null means open for write" )
(put   'close 'helptext "(close fh)" )
(put   'put 'helptext "(put atom propname propval) " )
(put   'remprop 'helptext "(remprop atom propname)" )
(put   'get 'helptext "(get atom propname) returns property if it exists" )
(put   'implode 'helptext "opposite of explode" )
(put   'rplaca 'helptext "(rplaca (a b c) d gives (d b c)) modifies list in memory - side effects. Works on the cell it is given, so (rplaca (cdr x) d) changes x as well" )
(put   'rplacd 'helptext "rplacd (a b c) (f g) gives (a f g) modifies list in memory - side effects" )
(put   'writec 'helptext "like princ" )
(put   'writen 'helptext "like prin" )
(put   'append 'helptext "(append '(a b c) '(d e f)) returns ( a  b  c  d  e  f )" )
(put   'reverse 'helptext "(reverse '(a b c)) returns (c b a)" )
(put   'princ 'helptext "print elements with escaping on special chars in atoms" )
(put   'initturtle 'helptext "(initturtle 800 800) Sets up turtlegraphics." )
(put   'home 'helptext "(home) Moves to screen middle, no pen write. Returns (xdim ydim)" )
(put   'pendown 'helptext "(pendown 1) Pen down. (pendown 0) is up. Returns 0 or 1" )
(put   'setfill 'helptext "A 1 sets fill on for rectangles and circles" )
(put   'pencolour 'helptext "Set pencolour R G B" )
(put   'fillcolour 'helptext "Set fillcolour R G B" )
(put   'turn 'helptext "Turn turtle head by relative angle (degrees)" )
(put   'turnto 'helptext "Turn turtle head to angle (degrees)" )
(put   'move 'helptext "(move magnitude) moves a line, will draw if pen down." )
(put   'moveto 'helptext "(moveto x y) Move pen to coords.  Will draw line if pen down." )
(put   'circle 'helptext "(circle radius) Draw a circle, can be filled" )
(put   'ellipse 'helptext "(ellipse rada radb) Draw an ellipse, can be filled" )
(put   'rectangle 'helptext "(rectangle width height) Draw a rectangle, can be filled" )
(put   'onscreen 'helptext "Return 1 if pen is on screen" )
(put   'polygon 'helptext "(polygon nsides length) Draw a polygon, does this by lines, cannot be filled" )
(put   'let 'helptext "(let ((a 1) (b 2)) forms) local variables, all vals evaluated before any is bound" )
(put   'let* 'helptext "(let* ((a 1) (b a)) forms) like let, but each val can use the vars before it" )
(put   'compex 'helptext "(compex N) mode: 0 interpret (default), 1 defun'd functions run compiled,
2 both, warns if results differ. (compex 4) clears all compiled code and resets the compiler,
keeping the mode, so functions are compiled again from their current definitions (not
allowed inside a compiled function or in the arguments of a call of one). Returns (bytes-used store-size).
(compex form) compiles form. A function redefined after it was compiled may still run its
old body from compiled callers until (compex 4); aarch64, x86_64." )
(put   'defined 'helptext "(defined x) true if the atom x is already defined (has a value or is a Subr), else null. An atom x is not evaluated so it can be undefined. A list such as (defined 'x) is evaluated first and the atom it gives is tested" )

